/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package checkbox;

import javax.swing.JOptionPane;

/**
 *
 * @author Laura
 */
public class AcaoComunitariaGUI extends javax.swing.JFrame {

    /**
     * Creates new form AcaoGUI
     */
    public AcaoComunitariaGUI() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbSegunda = new javax.swing.JCheckBox();
        jcbTerca = new javax.swing.JCheckBox();
        jcbQuarta = new javax.swing.JCheckBox();
        jcbQuinta = new javax.swing.JCheckBox();
        jcbSexta = new javax.swing.JCheckBox();
        jbConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Ação Comunitária");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Escolha três dias da semana:");

        jcbSegunda.setText("Segunda-feira");

        jcbTerca.setText("Terça-feira");

        jcbQuarta.setText("Quarta-Feira");

        jcbQuinta.setText("Quinta-Feira");

        jcbSexta.setText("Sexta-Feira");

        jbConfirmar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbConfirmar.setText("Confirmar");
        jbConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbConfirmar)
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbSexta)
                            .addComponent(jcbQuinta)
                            .addComponent(jcbTerca)
                            .addComponent(jLabel2)
                            .addComponent(jcbSegunda)
                            .addComponent(jcbQuarta)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jcbSegunda)
                .addGap(7, 7, 7)
                .addComponent(jcbTerca, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbQuarta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbQuinta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbSexta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jbConfirmar)
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConfirmarActionPerformed
        // TODO add your handling code here:
        int quantidadeDias = 0;
        String diasMarcados = "";
        if(jcbSegunda.isSelected()) {
            quantidadeDias++;
            diasMarcados += "Segunda-Feira\n";
        }
        if(jcbTerca.isSelected()) {
            quantidadeDias++;
            diasMarcados += "Terça-Feira\n";
        }
        if(jcbQuarta.isSelected()) {
            quantidadeDias++;
            diasMarcados += "Quarta-Feira\n";
        }
        if(jcbQuinta.isSelected()) {
            quantidadeDias++;
            diasMarcados += "Quinta-Feira\n";
        }
        if(jcbSexta.isSelected()) {
            quantidadeDias++;
            diasMarcados += "Sexta-Feira\n";
        }
        if(quantidadeDias<3) {
            JOptionPane.showMessageDialog(null, "Você escolheu poucos dias. " + "Portanto, deve escolher 3 dias.");
            return;
        }
        if(quantidadeDias>3) {
            JOptionPane.showMessageDialog(null, "Você escolheu muitos dias. " + "Portanto, deve escolher 3 dias.");
            return;
        }
         JOptionPane.showMessageDialog(null, "Você escolheu " + quantidadeDias + " dias.\n" + diasMarcados);
    }//GEN-LAST:event_jbConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcaoComunitariaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcaoComunitariaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcaoComunitariaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcaoComunitariaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcaoComunitariaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbConfirmar;
    private javax.swing.JCheckBox jcbQuarta;
    private javax.swing.JCheckBox jcbQuinta;
    private javax.swing.JCheckBox jcbSegunda;
    private javax.swing.JCheckBox jcbSexta;
    private javax.swing.JCheckBox jcbTerca;
    // End of variables declaration//GEN-END:variables
}
