/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pesquisa;

/**
 *
 * @author Laura
 */
public class PesquisaGUI extends javax.swing.JFrame {

    /**
     * Creates new form PesquisaGUI
     */
    public PesquisaGUI() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcbLendo = new javax.swing.JCheckBox();
        jcbEstudando = new javax.swing.JCheckBox();
        jcbJogando = new javax.swing.JCheckBox();
        jcbDormindo = new javax.swing.JCheckBox();
        jcbAssistindo = new javax.swing.JCheckBox();
        jcbConversando = new javax.swing.JCheckBox();
        jcbOuvindo = new javax.swing.JCheckBox();
        jbEnviar = new javax.swing.JButton();
        jlSaida = new javax.swing.JLabel();
        jlTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("O que mais estou fazendo nas horas vagas desta semana? ");

        jLabel2.setText("Você pode marcar mais de uma opção");

        jcbLendo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbLendo.setText("Lendo");

        jcbEstudando.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbEstudando.setText("Estudando");

        jcbJogando.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbJogando.setText("Jogando jogos");

        jcbDormindo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbDormindo.setText("Dormindo");

        jcbAssistindo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbAssistindo.setText("Assistindo filmes");

        jcbConversando.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbConversando.setText("Conversando com os amigos");

        jcbOuvindo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcbOuvindo.setText("Ouvindo músicas");

        jbEnviar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbEnviar.setText("Enviar");
        jbEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbEnviar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(145, 145, 145)
                            .addComponent(jLabel2))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(69, 69, 69)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jcbEstudando)
                                .addComponent(jcbLendo)
                                .addComponent(jcbJogando)
                                .addComponent(jcbDormindo)
                                .addComponent(jcbAssistindo)
                                .addComponent(jcbConversando)
                                .addComponent(jcbOuvindo)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addComponent(jLabel1)))
                    .addComponent(jlSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jcbLendo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbEstudando)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbJogando)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbDormindo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbAssistindo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbConversando)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcbOuvindo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbEnviar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEnviarActionPerformed
        // TODO add your handling code here:
        int quantidadesAtividades = 0;
        String atividadesMarcadas = "";
        if(jcbLendo.isSelected()) {
            atividadesMarcadas += "Lendo, ";
        }
        if(jcbEstudando.isSelected()) {
            atividadesMarcadas += "estudando, ";
        }
        if(jcbJogando.isSelected()) {
            atividadesMarcadas += "jogando jogos, ";
        }
        if(jcbDormindo.isSelected()) {
            atividadesMarcadas += "dormindo, ";
        }
        if(jcbAssistindo.isSelected()) {
            atividadesMarcadas += "assistindo filmes, ";
        }
        if(jcbConversando.isSelected()) {
            atividadesMarcadas += "conversando com os amigos, ";
        }
        if(jcbOuvindo.isSelected()) {
            atividadesMarcadas += "ouvindo músicas.";
        }
        if(atividadesMarcadas.equals("")) {
            jlSaida.setText("Você não escolheu nenhuma atividade.");
            return;
        }
        jlTitulo.setText("Atividades que estão sendo realizadas:");
        jlSaida.setText(atividadesMarcadas);
    }//GEN-LAST:event_jbEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesquisaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbEnviar;
    private javax.swing.JCheckBox jcbAssistindo;
    private javax.swing.JCheckBox jcbConversando;
    private javax.swing.JCheckBox jcbDormindo;
    private javax.swing.JCheckBox jcbEstudando;
    private javax.swing.JCheckBox jcbJogando;
    private javax.swing.JCheckBox jcbLendo;
    private javax.swing.JCheckBox jcbOuvindo;
    private javax.swing.JLabel jlSaida;
    private javax.swing.JLabel jlTitulo;
    // End of variables declaration//GEN-END:variables
}
