/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Laura
 */
public class formulario extends javax.swing.JFrame {

    /**
     * Creates new form formulario
     */
    public formulario() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgQuestaoUm = new javax.swing.ButtonGroup();
        bgQuestaoDois = new javax.swing.ButtonGroup();
        bgQuestaoTres = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jrbSoftware = new javax.swing.JRadioButton();
        jrbHardware = new javax.swing.JRadioButton();
        jrbPerifericos = new javax.swing.JRadioButton();
        jrbModem = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jrbBit = new javax.swing.JRadioButton();
        jrbByte = new javax.swing.JRadioButton();
        jrbMicrobyte = new javax.swing.JRadioButton();
        jrbMinibite = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jrbMilQuilobyte = new javax.swing.JRadioButton();
        jrbDezBits = new javax.swing.JRadioButton();
        jrbMilMegabyte = new javax.swing.JRadioButton();
        jrbDezMilBytes = new javax.swing.JRadioButton();
        jbSubmeter = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("O termo técnico para designar a parte física do computador é:");

        bgQuestaoUm.add(jrbSoftware);
        jrbSoftware.setText("Software");

        bgQuestaoUm.add(jrbHardware);
        jrbHardware.setText("Hardware");

        bgQuestaoUm.add(jrbPerifericos);
        jrbPerifericos.setText("Periféricos");

        bgQuestaoUm.add(jrbModem);
        jrbModem.setText("Modem");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("À menor quantidade de informação binária chama-se:");

        bgQuestaoDois.add(jrbBit);
        jrbBit.setText("Bit");

        bgQuestaoDois.add(jrbByte);
        jrbByte.setText("Byte");

        bgQuestaoDois.add(jrbMicrobyte);
        jrbMicrobyte.setText("Microbyte");

        bgQuestaoDois.add(jrbMinibite);
        jrbMinibite.setText("Minibite");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("1 GigaByte corresponde aproximadamente a:");

        bgQuestaoTres.add(jrbMilQuilobyte);
        jrbMilQuilobyte.setText("1000 kB (quilobyte)");

        bgQuestaoTres.add(jrbDezBits);
        jrbDezBits.setText("10 bits");

        bgQuestaoTres.add(jrbMilMegabyte);
        jrbMilMegabyte.setText("1000 MB (megabyte)");

        bgQuestaoTres.add(jrbDezMilBytes);
        jrbDezMilBytes.setText("10000 bytes");

        jbSubmeter.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbSubmeter.setText("Submeter");
        jbSubmeter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSubmeterActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Questionário");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbSubmeter)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jrbPerifericos)
                        .addComponent(jrbSoftware)
                        .addComponent(jLabel1)))
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbDezMilBytes)
                            .addComponent(jrbMilMegabyte)
                            .addComponent(jrbDezBits)
                            .addComponent(jrbMilQuilobyte)
                            .addComponent(jrbMinibite)
                            .addComponent(jrbMicrobyte)
                            .addComponent(jrbBit)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jrbByte)
                            .addComponent(jrbModem)
                            .addComponent(jrbHardware)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbSoftware)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbHardware)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbPerifericos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbModem)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbBit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbByte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbMicrobyte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbMinibite)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbMilQuilobyte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbDezBits)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbMilMegabyte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrbDezMilBytes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jbSubmeter)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSubmeterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSubmeterActionPerformed
        // TODO add your handling code here:
        if (!perguntaRespondida(bgQuestaoUm)) {
            JOptionPane.showMessageDialog(null, "A questão 1 não foi respondida");
            return;
        }
        if (!perguntaRespondida(bgQuestaoDois)) {
            JOptionPane.showMessageDialog(null, "A questão 2 não foi respondida");
            return;
        }
        if (!perguntaRespondida(bgQuestaoTres)) {
            JOptionPane.showMessageDialog(null, "A questão 3 não foi respondida");
            return;
        }
        int acertos = 0;
        acertos += jrbHardware.isSelected() ? 1 : 0;
        acertos += jrbBit.isSelected() ? 1 : 0;
        acertos += jrbMilMegabyte.isSelected() ? 1 : 0;
        
        JOptionPane.showMessageDialog(null, "Quantidade de acertos: " + acertos);
    }//GEN-LAST:event_jbSubmeterActionPerformed

    private boolean perguntaRespondida(ButtonGroup pergunta) {
        return pergunta.getSelection() != null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgQuestaoDois;
    private javax.swing.ButtonGroup bgQuestaoTres;
    private javax.swing.ButtonGroup bgQuestaoUm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbSubmeter;
    private javax.swing.JRadioButton jrbBit;
    private javax.swing.JRadioButton jrbByte;
    private javax.swing.JRadioButton jrbDezBits;
    private javax.swing.JRadioButton jrbDezMilBytes;
    private javax.swing.JRadioButton jrbHardware;
    private javax.swing.JRadioButton jrbMicrobyte;
    private javax.swing.JRadioButton jrbMilMegabyte;
    private javax.swing.JRadioButton jrbMilQuilobyte;
    private javax.swing.JRadioButton jrbMinibite;
    private javax.swing.JRadioButton jrbModem;
    private javax.swing.JRadioButton jrbPerifericos;
    private javax.swing.JRadioButton jrbSoftware;
    // End of variables declaration//GEN-END:variables
}
